### ISSUE TITLE
Fails to build on non-Linux

### ISSUE THREAD

**Issue by jbeich** [MaxVerevkin/wl-gammarelay-rs#2]
Regressed by b469d9e9aa53. Affects [downstream package](https://www.freshports.org/accessibility/wl-gammarelay-rs). CC @unrelentingtech

- FreeBSD >= 13.0 has [memfd_create(3)](https://man.freebsd.org/memfd_create/3) but https://github.com/rust-lang/libc/commit/0a57541a7101 cannot be used due to https://github.com/rust-lang/libc/issues/570. `memfd_create` can be replaced with `shm_open(SHM_ANON, ...)` which is supported on all FreeBSD versions.
- OpenBSD has [shm_mkstemp(3)](https://man.openbsd.org/shm_mkstemp.3) but not exposed in `libc` crate
- DragonFly and NetBSD have neither

```rust
$ cargo build
[...]
error[E0433]: failed to resolve: could not find `MemfdOptions` in `memfd`
   --> src/wayland.rs:106:39
    |
106 |                     let file = memfd::MemfdOptions::new().create("ramp")?;
    |                                       ^^^^^^^^^^^^ could not find `MemfdOptions` in `memfd`

warning: unused import: `std::os::unix::io::AsRawFd`
  --> src/wayland.rs:12:5
   |
12 | use std::os::unix::io::AsRawFd;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0433`.
warning: `wl-gammarelay-rs` (bin "wl-gammarelay-rs") generated 1 warning
error: could not compile `wl-gammarelay-rs` due to previous error; 1 warning emitted
```

**Comment by jbeich** [comment]
Note, this may block updating [downstream package](https://repology.org/project/wl-gammarelay-rs/versions) in future.

**Comment by MaxVerevkin** [comment]
Thanks for the report!

I guess https://lib.rs/crates/shmemfdrs can be used?

**Comment by MaxVerevkin** [comment]
Please try https://github.com/MaxVerevkin/wl-gammarelay-rs/commit/5e836c6914f9ad4c259a273995bc3048cf42136f

**Comment by jbeich** [comment]
Builds fine on FreeBSD amd64 and works fine under Sway 1.7 now. Building on DragonFly or FreeBSD i386/aarch64/powerpc64/etc is blocked by https://github.com/unrelentingtech/shmemfdrs/issues/5.

**Comment by MaxVerevkin** [comment]
I'm okay with depending on a specific git commit instead of a tag if it helps.

**Comment by jbeich** [comment]
Should be ready now. Can you update dependencies or just `shmemfdrs`?
```diff
$ cargo update -p shmemfdrs
    Updating crates.io index
    Removing sc v0.2.7
    Updating shmemfdrs v0.1.1 -> v0.1.2
$ git diff
diff --git a/Cargo.lock b/Cargo.lock
index 66de8a7..9056685 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -660,12 +660,6 @@ version = "0.6.25"
 source = "registry+https://github.com/rust-lang/crates.io-index"
 checksum = "f497285884f3fcff424ffc933e56d7cbca511def0c9831a7f9b5f6153e3cc89b"
 
-[[package]]
-name = "sc"
-version = "0.2.7"
-source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "010e18bd3bfd1d45a7e666b236c78720df0d9a7698ebaa9c1c559961eb60a38b"
-
 [[package]]
 name = "scoped-tls"
 version = "1.0.0"
@@ -720,12 +714,11 @@ checksum = "ae1a47186c03a32177042e55dbc5fd5aee900b8e0069a8d70fba96a9375cd012"
 
 [[package]]
 name = "shmemfdrs"
-version = "0.1.1"
+version = "0.1.2"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "175eef7ea3471a106255cee9794bccfc3dc62832739526219fe0b795da0dd6fe"
+checksum = "2da0cd782f1ec8ff2ce0ad7f766d16cc355eadd887a863559bfc1d5d886cb3b8"
 dependencies = [
  "libc",
- "sc",
 ]
 
 [[package]]
```

**Comment by MaxVerevkin** [comment]
Done. Published a new version.
